name: call

on:
  workflow_call:
    inputs:
      test:
        type: string
        required: true
        description: test
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        description: Environment to run
        options:
        - dev
        - prod

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      VAR: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.env || inputs.test }}
    steps:
      - name: test
        run: |
          echo ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.env || inputs.test }}
          echo ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.env || inputs.test }} > test.txt
          cat test.txt
          echo ${{ inputs.test }}
          echo ${{ secrets.HOST == '' }}
          echo ${{ env.VAR == 'input test' }}
