name: cicd-dev

on:
  push:
    branches:
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH
        run: |
          echo "${{ secrets.SSH_KEY }}" > test
          cat test
          ssh -i test ${{ secrets.USERNAME }}@${{ secrets.HOST }}
          touch here.txt
          exit
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: next-cicd-dev:latest
      - name: Save Image
        run: docker save next-cicd-dev:latest > next-cicd-dev.tar
      - name: SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: "./next-cicd-dev.tar"
          target: "~/"