name: cicd-dev

on:
  push:
    branches:
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: next-cicd-dev:latest
      - name: Test
        run: docker run -d -p 4000:4000 -e PORT=4000 next-cicd-dev
      - name: Curl
        run: curl localhost:4000