name: cicd-dev

on:
  push:
    branches:
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: next-cicd-dev:latest
      - name: Save Image
        run: docker save next-cicd-dev:latest > next-cicd-dev.tar
      - name: SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: "./next-cicd-dev.tar"
          target: "~/"
      - name: Run Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            whoami
            docker load --input next-cicd-dev.tar
            docker stop $(docker ps -a -q --filter ancestor=next-cicd-dev)
            docker run -d --rm -p 4000:4000 -e PORT=4000 next-cicd-dev
            docker ps
            rm next-cicd-dev.tar