name: TEST

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          touch no1.tar
          echo "PART 1"
          [ -e no1.tar ] && echo "no1 exist"
          echo "PART 2"
          [ -e *.tar ] && echo "tar exist"
          echo "PART 3"
          [ -e *.asdfghjkl ] && echo "asdfghkl exist"
          echo "execute after check no such file"
