name: TEST

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        description: Environment to run
        options:
        - dev
        - prod

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo ${{ github.event.inputs.env }}
          echo 'TEST="${{ secrets.HOST }}"' >> $GITHUB_ENV
          echo $TEST
          echo ${GITHUB_REF#refs/heads/}
          echo ${GITHUB_REF##*/}
          echo 'BRANCH=$(echo ${{GITHUB_REF##*/}})'
          echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
          echo ${{ env.BRANCH == 'dev' }}
          echo ${{ env.BRANCH == 'main' }}
